# Generated by Django 5.2.17 on 2026-10-02 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline. It is shown in capitals.', max_length=160)),
                ('slug', models.SlugField(help_text='The last part of the web address. Filled in from the headline; avoid changing it after publishing, or old links break.', max_length=80, unique=True)),
                ('standfirst', models.TextField(help_text='The one or two sentences under the headline.')),
                ('body', models.TextField(help_text='The piece itself, in Markdown. A blank line starts a new paragraph, "## " a heading, "> " a pull quote, **bold**, *italic*, [link text](https://address).')),
                ('reading_minutes', models.PositiveSmallIntegerField(default=5, help_text='Shown next to the byline.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Empty: a draft only you can see. A time in the future: goes live by itself then.', null=True)),
                ('replies_open', models.BooleanField(default=True, help_text='Untick to stop new replies to this piece.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'piece',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Order on the coupon: 1, 2, 3…')),
                ('text', models.CharField(help_text='One sentence a reader can agree or disagree with.', max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.article')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor', models.UUIDField()),
                ('nickname', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1200)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Being checked'), (2, 'Published'), (3, 'Rejected'), (4, 'Waiting for the house')], default=1)),
                ('moderation_note', models.CharField(blank=True, help_text='Why the moderator rejected it or passed it to the house.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.article')),
            ],
            options={
                'verbose_name_plural': 'replies',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('house_reply', models.TextField(blank=True, help_text='Your answer to this argument. Shown on the piece.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.article')),
                ('claim', models.ForeignKey(blank=True, help_text='The claim it argues against. Empty: against the piece as a whole.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arguments', to='core.claim')),
                ('replies', models.ManyToManyField(blank=True, related_name='arguments', to='core.reply')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.UUIDField()),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, 'Agree'), (2, 'Disagree')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.claim')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('article', 'position'), name='one_claim_per_position'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('claim', 'visitor'), name='one_vote_per_visitor'),
        ),
    ]
